### ISSUE TITLE
cannot access some of the methods

### ISSUE THREAD

**Issue by GabrielLCHeng** [noxdafox/clipspy#35] opened 2020-06-08 10:11 UTC
![image](https://user-images.githubusercontent.com/19849113/84018896-28626a80-a9b3-11ea-9fbf-26f2e4a61cc2.png)

when I tried code this, the method 'make_instance' cannot be found. It showed some error. There are also some other methods which behave like this.
below is the error:

```
Traceback (most recent call last):
  File "C:\Users\GabrielLCH\Anaconda3\envs\krr_expert_system\lib\site-packages\clips\environment.py", line 84, in __getattr__
    return getattr(self._namespaces[attr], attr)
KeyError: 'make_instance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\clipspy tutor.py", line 50, in <module>
    instance = env.make_instance('(instance-name of MyClass (One 1) (Two 2))')
  File "C:\...\site-packages\clips\environment.py", line 87, in __getattr__
    (self.__class__.__name__, attr))
AttributeError: 'Environment' object has no attribute 'make_instance'
```

**Comment by noxdafox** [comment] 2020-06-08 14:20
Hello,

how did you install `clipspy`? Which version do you have installed?

**Comment by kiofings** [comment] 2020-06-09 08:48
I used pip install clipspy==0.3.2, with python 3.7

**Comment by noxdafox** [comment] 2020-09-03 14:16
Did you by chance also install PyCLIPS on your environment?

**Comment by lstarin** [comment] 2020-10-14 12:58
Hi, I have the same problem. I'm also using version 0.3.2.
Thanks!

**Comment by noxdafox** [comment] 2020-10-14 14:19
Could you please try installing the last version (`0.3.3`)?

**Comment by noxdafox** [comment] 2020-10-14 14:21
Now I see the problem, the `make_instance` method was added in [`clipspy:0.3.3`](https://github.com/noxdafox/clipspy/commit/4396c3c3e780b0424388ba9fbf4936d194c74629#diff-bc6fc3d86e3a9eda598671ddc632469108d795149af7259e470207d6443a75bc).

Please upgrade to the last version of it.

**Comment by lstarin** [comment] 2020-10-14 16:53
Thanks for your response!
I installed version 0.3.3 and I still have the same problem :-(

**Comment by noxdafox** [comment] 2020-10-14 18:14
Can you access to other class-related methods?

What if you try `env.find_instance`?

What is the output of: `dict(env._classes)`?

**Comment by lstarin** [comment] 2020-10-15 07:09
Now it is working, I reinstalled version 0.3.3 and restarted the computer, and now it's ok. Thanks!

**Comment by noxdafox** [comment] 2020-10-15 08:42
Closing this ticket as the root cause mostly was a "dirty environment".

**Closed by noxdafox** 2020-10-15 08:42 UTC
